### ISSUE TITLE
Crash when sending /bb fr Hello world

### ISSUE THREAD

**Issue by AcidNinjaFWHR** [taikedz/minetest-babelfish#1]
ServerError: Lua: Runtime error from mod 'babelfish' in callback on_chat_message(): .../minetest/.minetest/mods/babelfish/yandex_engine.lua:107: attempt to concatenate field 'key' (a nil value)

**Comment by taikedz** [comment]
Fixed since 8e400cc

**Comment by AcidNinjaFWHR** [comment]
Hummm, weird since we're using 9a152c55f50851d03294ecb158c598d9edc57583
See here: https://github.com/Mynetest/Mynetest-server/commit/3466662b316981328a11f302a0ebb7da1c977f05

**Comment by taikedz** [comment]
Ah right - it seems you have not configured `babelfish.key` in your `minetest.conf` file? You need a Yandex API key to use the Yandex service.

**Comment by taikedz** [comment]
Confirmed - you have not configured your minetest.conf with an API key

I've added some checking so that when the key is not configured at least it will not crash the game 87fb400
